/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2E0HXrqP7yV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Layout() {
  return (
    <main className="flex flex-col gap-12 md:gap-20">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  John Doe
                </h1>
                <p className="text-gray-500 md:text-xl dark:text-gray-400">Game Developer Producer</p>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  게임 기획자 김진서입니다<div className=""></div>
                </p>
              </div>
            </div>
            <img
              alt="John Doe"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Past Projects</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Explore a selection of John Doe&apos;s past game projects, showcasing his expertise in game development and
              production.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-950 dark:hover:shadow-lg dark:border-gray-800">
              <img
                alt="Project 1"
                className="mb-4 aspect-[4/3] w-full rounded-md object-cover"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <h3 className="text-lg font-semibold">Cyberpunk Odyssey</h3>
              <p className="text-gray-500 dark:text-gray-400">
                An immersive cyberpunk-themed open-world adventure game that blends action, RPG, and stealth elements.
              </p>
            </div>
            <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-950 dark:hover:shadow-lg dark:border-gray-800">
              <img
                alt="Project 2"
                className="mb-4 aspect-[4/3] w-full rounded-md object-cover"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <h3 className="text-lg font-semibold">Fantasy Realms</h3>
              <p className="text-gray-500 dark:text-gray-400">
                A high-fantasy RPG that immerses players in a world of magic, adventure, and epic storytelling.
              </p>
            </div>
            <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-950 dark:hover:shadow-lg dark:border-gray-800">
              <img
                alt="Project 3"
                className="mb-4 aspect-[4/3] w-full rounded-md object-cover"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <h3 className="text-lg font-semibold">Retro Arcade Blast</h3>
              <p className="text-gray-500 dark:text-gray-400">
                A nostalgic arcade-style game that pays homage to the golden age of gaming with its vibrant visuals and
                addictive gameplay.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">About</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Experienced Game Developer and Producer
                </h2>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  With over 12 years of experience in the gaming industry, John Doe has honed his skills in game
                  development, project management, and creative direction. He has a proven track record of delivering
                  successful and critically acclaimed titles, working closely with talented teams to bring innovative
                  ideas to life.
                </p>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  John&apos;s expertise spans a wide range of game genres, from open-world adventures to fast-paced action
                  games. He is passionate about storytelling, player-centric design, and pushing the boundaries of
                  what's possible in the medium of interactive entertainment.
                </p>
              </div>
            </div>
            <img
              alt="About"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid items-center justify-center gap-4 text-center">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get in Touch</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Have a project in mind or just want to say hello? Fill out the form below and John will get back to you
                as soon as possible.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="grid gap-4">
                <Input placeholder="Name" type="text" />
                <Input placeholder="Email" type="email" />
                <Textarea placeholder="Message" rows={4} />
                <Button type="submit">Send Message</Button>
              </form>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}
